name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key for .env.testing
      run: php artisan key:generate --env=testing
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/pest

  build:

    runs-on: ubuntu-latest
    needs: ["test"]

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    
    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build for production
      run: ./build.sh
    
    - name: Debug builds dir
      run: ls -lah builds
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ github.sha }}.zip"
        path: "./builds/${{ github.sha }}.zip"


  deploy-staging:

    runs-on: ubuntu-latest
    environment: staging
    needs: ["test", "build"]

    steps:
    - name: Deploy staging
      run: |
        curl -X POST https://forge.laravel.com/servers/some-server/sites/some-site/deploy/http?token=some-token \
            -d "forge_deploy_commit=$GITHUB_SHA" -d "forge_deploy_author=$GITHUB_TRIGGERING_ACTOR"

  deploy-production:

    runs-on: ubuntu-latest
    environment: production
    needs: ["test", "build", "deploy-staging"]

    steps:
    - name: Deploy production
      run: | 
        curl -X POST https://forge.laravel.com/servers/some-server/sites/some-site/deploy/http?token=some-token \
            -d "forge_deploy_commit=$GITHUB_SHA" -d "forge_deploy_author=$GITHUB_TRIGGERING_ACTOR"

